version: "3.9"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # hot reloading for React
      - REACT_APP_API_URL=http://localhost:5000/api

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: health-diary-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: health_app
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

