"""Add created_at to raw_entries

Revision ID: 045300a4ce66
Revises: b069dced14ef
Create Date: 2025-07-24 12:37:32.946257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045300a4ce66'
down_revision = 'b069dced14ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_entries', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
