"""Add entry_date to raw_entries

Revision ID: b069dced14ef
Revises: 5c7dbb0a595f
Create Date: 2025-07-24 11:07:54.156861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b069dced14ef'
down_revision = '5c7dbb0a595f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_entries', schema=None) as batch_op:
        batch_op.drop_column('entry_date')

    # ### end Alembic commands ###
